### PR TITLE
Fixes #1395 - Allow model names with "."s

### LINKED ISSUE #1395: A dot in either the model name, or a property name throws an error in WebWorker
In the following spec, `desciption` should have a validation error, but because there is a dot in `One.Two` it simply throws an error in the conole. The error occurs in the WebWorker.

```yaml
swagger: '2.0'

info:
  version: 1.0.0
  title: Dot in Model name ( or properties, same applies )

definitions:
  One.Two:
    type: object
    desciption: this shoud be spelled "description"
```

> My guess is that its failing to de-reference the path, due to the dot.

`Object {swaggerEditor: "3.0.13/g9e127dc-dirty", swaggerUi: "3.0.17/g165c1d7"}`

Error: 
```
blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13 Worker caught an error: TypeError: Cannot read property '1' of null
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:2:3541
    at Array.map (native)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:2:3471)
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:3446
    at Array.map (native)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:3349)
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:823
    at r (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22530)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22586)
    at s (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22835)
```
```
VM1555:27 Error: Cannot read property '1' of null
    at t._callbacks.(anonymous function) (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1596)
    at i (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1302)
    at Worker.<anonymous> (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1405)
```

### PR DESCRIPTION
**Pull request by owenconti**
Fixes #1395 

I'm not 100% confident this fix is correct, but I added a test and tested with various specs and they all seem to work as I _think_ they should.

Here's a screenshot:

screen shot 2017-07-17 at 8 19 08 pm

### CODE REVIEW

**Comment by shockey** [comment]
Well, this is embarrassing.... The path translator tests weren't running, because of the `just-test-in-node` script definition.

Just fixed that, looking more into this now.

File: test/path-translator.js [hunk 1]
```diff
@@ -70,7 +70,8 @@ describe("validation plugin - path translator", function(){
       let jsSpec = {
         definitions: {
           "One.Two": {
-            a: "1"
+            a: "1",
+            abc123: "1"
```
Comment (shockey) [inline test/path-translator.js]: @owenconti, apologies for tripping you up here 😬

Comment (owenconti) [inline test/path-translator.js]: No worries, it took me a while to figure out what was missing, ha.
