### PR TITLE
install updated version of Source Code Pro from GitHub

### LINKED ISSUE #665: Incorrect cursor position when writing in non-latin text (e.g. in Russian)
AFAIK Ace editor supports only monospace fonts and used in Swagger Editor Source Code Pro font doesn't have Cyrillic glyphs, so browser uses some other, non monospace, font.

Here is example of how it looks like if I type "ЩЩЩ":
selection_013

Notice cursor floating in the center of the letter.

Here is how it looks if I disable Source Code Pro font in Firefox style editor:

selection_014

### PR DESCRIPTION
**Pull request by rutsky**
Fixes #665.

There are following issues that I see with these changes:

1. Source Code Pro fonts are being copied in `dist/styles/` directory intead of `dist/fonts`, due to relative paths in Source Code Pro's [source-code-pro.css](https://github.com/adobe-fonts/source-code-pro/blob/release/source-code-pro.css) stylesheet.

2. I specified Source Code Pro version by git sha1 hash, because [fixes](https://github.com/adobe-fonts/source-code-pro/issues/110) in `source-code-pro.css` are not in released (tagged) version yet.

### CODE REVIEW

File: grunt/copy.js [hunk 1]
```diff
@@ -61,5 +61,20 @@ module.exports = {
       'mode-yaml.js',
       'mode-json.js'
     ],
+  },
+  source_code_pro: {
```
Comment (mohsen1) [inline grunt/copy.js]: Use cameCase instead.

Comment (rutsky) [inline grunt/copy.js]: Fixed.

**Comment by mohsen1** [comment]
Thanks!
